- name: Check directory
  stat:
    path: "{{ starrocks_home_dir }}"
  register: dir_result

- name: 下载压缩包
  ansible.builtin.get_url:
    url: "http://i-ansible.oss-cn-hangzhou-internal.aliyuncs.com/{{ starrocks_tar_name }}"
    validate_certs: false
    dest: "/tmp/{{ starrocks_tar_name }}"
    mode: "0755"
    force: true
    owner: "{{ starrocks_install_user }}"
    group: "{{ starrocks_install_user }}"
  when: not dir_result.stat.exists

- name: 创建目录
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    mode: "0755"
  become_user: "{{ starrocks_install_user }}"
  with_items:
    - "{{ starrocks_install_dir }}"
    - "{{ starrocks_fe_meta_dir }}"

- name: 解压
  ansible.builtin.unarchive:
    remote_src: true
    src: "/tmp/{{ starrocks_tar_name }}"
    dest: "{{ starrocks_install_dir }}"
    owner: "{{ starrocks_install_user }}"
    group: "{{ starrocks_install_user }}"
  become_user: "{{ starrocks_install_user }}"
  when: not dir_result.stat.exists


- name: 先 执行扩容操作
  ansible.builtin.shell:
    cmd: >
         /usr/bin/mysql -h{{ starrocks_fe_leader_priority }} -P9030 -uroot -e "{{ item }}"
  with_items:
    - ALTER SYSTEM ADD FOLLOWER '{{ starrocks_add_fe_priority }}:9010'
  changed_when: false
  ignore_errors: true

- name: 临时启动 Helper 节点
  ansible.builtin.shell:
    chdir: "{{ starrocks_home_dir }}"
    cmd: source ~/.bashrc.d/java_env11.sh; ./fe/bin/start_fe.sh --helper {{ starrocks_fe_leader_priority }}:9010 --daemon
  become_user: "{{ starrocks_install_user }}"

- name: 检查端口是否运行
  ansible.builtin.wait_for:
    port: "{{ item }}"
    state: started
    delay: 4
    timeout: 30
  with_items:
    - 8030
    - 9020
    - 9030

- name: 查询扩容结果
  ansible.builtin.shell:
    cmd: >
         /usr/bin/mysql -h{{ starrocks_fe_leader_priority }} -P9030 -uroot -e "{{ item }}"
  with_items:
    - show frontends\G;
  changed_when: false
  register: print_result

- name: 停止 Helper 节点
  ansible.builtin.shell:
    chdir: "{{ starrocks_home_dir }}"
    cmd: ./fe/bin/stop_fe.sh

- name: 复制启动文件
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ starrocks_service_dir }}/{{ item }}"
    mode: "0755"
    owner: root
    group: root
  with_items:
    - "{{ starrocks_fe_service_file }}"
  notify: Reload StarRocks FE

- name: 立即执行 handler
  ansible.builtin.meta: flush_handlers

- name: 检查端口是否运行
  ansible.builtin.wait_for:
    port: "{{ item }}"
    state: started
    delay: 5
    timeout: 30
  with_items:
    - 8030
    - 9020
    - 9030