- name: 安装 StarRocks
  hosts: deploy
  become: true
  vars:
    java_home: "/data/service/jdk-11.0.2"
    starrocks_version: "3.1.2"
    starrocks_tar_name: "StarRocks-{{ starrocks_version }}.tar.gz"
    starrocks_install_dir: "/data/service"
    starrocks_home_dir: "{{ starrocks_install_dir }}/StarRocks-{{ starrocks_version }}"
    starrocks_install_user: "ecs-user"
    starrocks_service_type: "supervisord"
    starrocks_service_dir: "/etc/supervisord.d/conf.d"
    # FE config
    starrocks_fe_meta_dir: "{{ starrocks_home_dir }}/fe/meta"
    starrocks_fe_service_file: "starrocks-fe-supervisord.ini"
    starrocks_fe_service_name: "starrocks-fe"
    starrocks_be_storage_dir: "{{ starrocks_home_dir }}/be/storage"
    starrocks_be_service_file: "starrocks-be-supervisord.ini"
    starrocks_be_service_name: "starrocks-be"
    starrocks_cn_service_file: "starrocks-cn-supervisord.ini"
    starrocks_cn_service_name: "starrocks-cn"
    # 扩容
    starrocks_add_be_priority: "172.16.180.72"
    starrocks_add_cn_priority: "172.16.180.72"

  handlers:
    - name: "Reload StarRocks FE"
      community.general.supervisorctl:
        config: "/etc/supervisord.d/supervisor.conf"
        name: "{{ starrocks_fe_service_name }}"
        state: restarted
      changed_when: false
    - name: "Reload StarRocks BE"
      community.general.supervisorctl:
        config: "/etc/supervisord.d/supervisor.conf"
        name: "{{ starrocks_be_service_name }}"
        state: restarted
      changed_when: false
    - name: "Reload StarRocks CN"
      community.general.supervisorctl:
        config: "/etc/supervisord.d/supervisor.conf"
        name: "{{ starrocks_cn_service_name }}"
        state: restarted
      changed_when: false
  tasks:
    - name: 初始化
      ansible.builtin.import_tasks: "setup-task.yaml"
      tags:
        - init

    - name: FE 节点初始化
      ansible.builtin.import_tasks: "init-cluster-task.yaml"
      tags:
        - init

    - name: 扩容 BE
      ansible.builtin.import_tasks: "add-be-task.yaml"
      tags:
        - add-be

    - name: 扩容 CN
      ansible.builtin.import_tasks: "add-cn-task.yaml"
      tags:
        - add-cn

    - name: 扩容 FE
      ansible.builtin.import_tasks: "add-fe-task.yaml"
      tags:
        - add-fe
