- name: 安装 MySQL
  hosts: "*"
  become: true
  handlers:
    - name: "重启MySQL"
      community.general.supervisorctl:
        config: "/etc/supervisord.d/supervisord.conf"
        name: "{{ mysql_service_name }}"
        state: restarted
      changed_when: false
  tasks:
    # - name: 下载 Linux 通用包
    #   ansible.builtin.get_url:
    #     url: "{{ mysql_down_base_url }}{{ mysql_tar_name }}"
    #     validate_certs: false
    #     dest: "/tmp/{{ mysql_tar_name }}"
    #     mode: "0755"
    #     force: true
    #     owner: "{{ mysql_install_user }}"
    #     group: "{{ mysql_install_user }}"

    # - name: 解压 Linux 通用包
    #   ansible.builtin.unarchive:
    #     src: /tmp/{{ mysql_tar_name }}
    #     dest: "{{ mysql_install_dir }}"
    #     remote_src: true
    #     owner: "{{ mysql_install_user }}"
    #     group: "{{ mysql_install_user }}"

    - name: 安装MySQL8.0
      ansible.builtin.import_tasks: "deploy-mysql-8_task.yaml"
      when: mysql_ignore_table_name == 'N'

    - name: 安装MySQL8.0(忽略大小写)
      ansible.builtin.import_tasks: "deploy-mysql-8_01_task.yaml"
      when: mysql_ignore_table_name == 'Y'
